# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
# os:
#   - linux
#   - osx
# julia:
#   - 0.6
#   - 0.7
# for now we depend on SampledSignals master. Once it's tagged we can remove
# this logic.
matrix:
  include:
    - julia: 0.6
      os: linux
      env: UPDATECMD='Pkg.add("SampledSignals"); Pkg.checkout("SampledSignals")'
    - julia: 0.7
      os: linux
      env: UPDATECMD='using Pkg; Pkg.add(PackageSpec(name="SampledSignals", rev="master"))'
    - julia: 0.6
      os: osx
      env: UPDATECMD='Pkg.add("SampledSignals"); Pkg.checkout("SampledSignals")'
    - julia: 0.7
      os: osx
      env: UPDATECMD='using Pkg; Pkg.add(PackageSpec(name="SampledSignals", rev="master"))'
branches:
  only:
    master
notifications:
  email: false
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e "$UPDATECMD"
 - julia -e 'Pkg.clone(pwd()); Pkg.build("LibSndFile"); Pkg.test("LibSndFile"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("LibSndFile")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
