# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
notifications:
  email: false
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone(pwd()); Pkg.build("LibSndFile"); Pkg.test("LibSndFile"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("LibSndFile")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
